[package]
name = "tunstile_tunnel"
version = "0.0.1"
edition = "2024"
description = "A pure Rust implementation of the Wireguard protocol"
license = "MIT"
repository = "https://github.com/n8mgr/tunstile"
keywords = ["wireguard", "vpn", "tunnel", "networking"]

[dependencies]
log = "0.4.33"
quinn-udp = { version = "0.6.1", features = ["fast-apple-datapath"] }
rand = "0.10.2"
tunstile_protocol = { version = "0.0.1", path = "../protocol", features = ["std"] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["fs", "net", "rt", "rt-multi-thread", "sync", "macros", "io-util", "time"] }

[dev-dependencies]
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
tokio = { version = "1.52.3", features = ["test-util"] }
criterion = { version = "0.8", features = ["async_tokio"] }
env_logger = "0.11.11"
etherparse = "0.20.3"

[[bench]]
name = "tunnel"
harness = false
