name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare releases')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
      - name: Setup Knope
        uses: knope-dev/action@19617851f9f13ab2f27a05989c55efb18aca3675 # v2.1.2
      - name: Prepare Release
        id: prepare
        run: knope prepare-release --verbose
        continue-on-error: true
      - name: Create Pull Request
        if: steps.prepare.outcome == 'success'
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          delete-branch: true
          commit-message: "chore: prepare releases"
          title: Release Versions
          base: master
          branch: release
          body: |
            This PR was automatically created to prepare the release versions. Merge it when you are ready to release. See the changelogs for more details.
